---
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  kustomize.component: cert-manager
configMapGenerator:
- envs:
  - params.env
  name: cert-manager-kube-params-parameters
configurations:
- params.yaml
generatorOptions:
  disableNameSuffixHash: true
kind: Kustomization
namespace: kube-system
resources:
- role-binding.yaml
- role.yaml
vars:
- fieldref:
    fieldpath: data.certManagerNamespace
  name: certManagerNamespace
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: cert-manager-kube-params-parameters
