---
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  kustomize.component: cluster-local-gateway
configMapGenerator:
- envs:
  - params.env
  name: cluster-local-gateway-parameters
configurations:
- params.yaml
kind: Kustomization
resources:
- cluster-role-binding.yaml
- cluster-role.yaml
- deployment.yaml
- horizontal-pod-autoscaler.yaml
- namespace.yaml
- pod-disruption-budget.yaml
- service-account.yaml
- service.yaml
vars:
- fieldref:
    fieldpath: data.namespace
  name: namespace
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: cluster-local-gateway-parameters
