---
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  kustomize.component: metacontroller
images:
- name: docker.artifactory.ikarem.io/user/ravi/kubeflow/metacontroller
  newName: docker.artifactory.ikarem.io/user/ravi/kubeflow/metacontroller
  newTag: v0.3.0
kind: Kustomization
namespace: kubeflow
resources:
- cluster-role-binding.yaml
- crd.yaml
- service-account.yaml
- stateful-set.yaml
