---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cache-deployer
  name: cache-deployer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache-deployer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cache-deployer
    spec:
      containers:
      - env:
        - name: NAMESPACE_TO_WATCH
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: docker.artifactory.ikarem.io/user/ravi/kubeflow/ml-pipeline/cache-deployer:1.0.0
        imagePullPolicy: Always
        name: main
        resources:
          limits:
            memory: 300Mi
          requests:
            cpu: 50m
            memory: 300Mi
      restartPolicy: Always
      serviceAccountName: kubeflow-pipelines-cache-deployer-sa
