---
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app.kubernetes.io/component: minio
  app.kubernetes.io/name: minio
kind: Kustomization
patchesStrategicMerge:
- deployment-patch.yaml
resources:
- ../../../upstream/env/platform-agnostic/minio/
- ../../overlays/application/application.yaml
