---
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  kustomize.component: pytorch-operator
images:
- name: docker.artifactory.ikarem.io/user/ravi/kubeflow/kubeflow-images-public/pytorch-operator
  newName: docker.artifactory.ikarem.io/user/ravi/kubeflow/kubeflow-images-public/pytorch-operator
  newTag: vmaster-gd596e904
kind: Kustomization
namespace: kubeflow
resources:
- cluster-role-binding.yaml
- cluster-role.yaml
- deployment.yaml
- service-account.yaml
- service.yaml
