---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mxnet-operator
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'false'
      labels:
        name: mxnet-operator
    spec:
      containers:
      - command:
        - /opt/kubeflow/mxnet-operator.v1
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: docker.artifactory.ikarem.io/user/ravi/kubeflow/mxnet-operator:v1.0.0-20200625
        imagePullPolicy: Always
        name: mxnet-operator
        resources:
          limits:
            memory: 300Mi
          requests:
            cpu: 50m
            memory: 300Mi
      serviceAccountName: mxnet-operator
