---
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  kustomize.component: mxnet-operator
images:
- name: docker.artifactory.ikarem.io/user/ravi/kubeflow/mxnet-operator
  newName: docker.artifactory.ikarem.io/user/ravi/kubeflow/mxnet-operator
  newTag: v1.0.0-20200625
kind: Kustomization
namespace: kubeflow
resources:
- cluster-role-binding.yaml
- cluster-role.yaml
- crd.yaml
- deployment.yaml
- service-account.yaml
