---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: katib
    component: ui
  name: katib-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: katib
      component: ui
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'false'
      labels:
        app: katib
        component: ui
      name: katib-ui
    spec:
      containers:
      - args:
        - --port=8080
        command:
        - ./katib-ui
        env:
        - name: KATIB_CORE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: docker.artifactory.ikarem.io/user/ravi/kubeflow/kubeflow-images-public/katib/v1alpha3/katib-ui:917164a
        imagePullPolicy: IfNotPresent
        name: katib-ui
        ports:
        - containerPort: 8080
          name: ui
        resources:
          limits:
            memory: 300Mi
          requests:
            cpu: 50m
            memory: 300Mi
      serviceAccountName: katib-ui
