---
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  kustomize.component: tf-job-operator
images:
- name: docker.artifactory.ikarem.io/user/ravi/kubeflow/kubeflow-images-public/tf_operator
  newName: docker.artifactory.ikarem.io/user/ravi/kubeflow/kubeflow-images-public/tf_operator
  newTag: vmaster-ga2ae7bff
kind: Kustomization
namespace: kubeflow
resources:
- cluster-role-binding.yaml
- cluster-role.yaml
- deployment.yaml
- service-account.yaml
- service.yaml
