---
apiVersion: v1
imagePullSecrets:
- name: artifactory-registry-secret
kind: ServiceAccount
metadata:
  labels:
    app: tf-job-dashboard
  name: tf-job-dashboard
---
apiVersion: v1
imagePullSecrets:
- name: artifactory-registry-secret
kind: ServiceAccount
metadata:
  labels:
    app: tf-job-operator
  name: tf-job-operator
