---
apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
- behavior: merge
  literals:
  - issuer="http://dex.auth.svc.cluster.local:5556/dex"
  - oidc_redirect_uris=["/login/oidc"]
  - client_id="kubeflow-oidc-authservice"
  name: dex-parameters
- envs:
  - ./config/params.env
  name: dex-config
generatorOptions:
  disableNameSuffixHash: true
kind: Kustomization
namespace: auth
patchesStrategicMerge:
- configmap_patch.yaml
resources:
- ../../../../dex-auth/dex-crds/overlays/istio
vars:
- fieldref:
    fieldpath: data.static_email
  name: config_static_email
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: dex-config
- fieldref:
    fieldpath: data.static_password_hash
  name: config_static_password_hash
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: dex-config
