---
apiVersion: caching.internal.knative.dev/v1alpha1
kind: Image
metadata:
  labels:
    serving.knative.dev/release: v0.11.2
  name: queue-proxy
  namespace: knative-serving
spec:
  image: docker.artifactory.ikarem.io/user/ravi/kubeflow/knative-releases/knative.dev/serving/cmd/queue:f9df2ae4-28f4-467b-9155-8159412381df
