---
apiVersion: v1
imagePullSecrets:
- name: artifactory-registry-secret
kind: ServiceAccount
metadata:
  labels:
    serving.knative.dev/release: v0.11.2
  name: controller
  namespace: knative-serving
