---
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  kustomize.component: cert-manager
configMapGenerator:
- envs:
  - params.env
  name: cert-manager-parameters
configurations:
- params.yaml
generatorOptions:
  disableNameSuffixHash: true
images:
- name: docker.artifactory.ikarem.io/user/ravi/kubeflow/jetstack/cert-manager-cainjector
  newName: docker.artifactory.ikarem.io/user/ravi/kubeflow/jetstack/cert-manager-cainjector
  newTag: v0.11.0
- name: docker.artifactory.ikarem.io/user/ravi/kubeflow/jetstack/cert-manager-controller
  newName: docker.artifactory.ikarem.io/user/ravi/kubeflow/jetstack/cert-manager-controller
  newTag: v0.11.0
- name: docker.artifactory.ikarem.io/user/ravi/kubeflow/jetstack/cert-manager-webhook
  newName: docker.artifactory.ikarem.io/user/ravi/kubeflow/jetstack/cert-manager-webhook
  newTag: v0.11.0
kind: Kustomization
namespace: cert-manager
resources:
- namespace.yaml
- api-service.yaml
- cluster-role-binding.yaml
- cluster-role.yaml
- deployment.yaml
- mutating-webhook-configuration.yaml
- service-account.yaml
- service.yaml
- validating-webhook-configuration.yaml
vars:
- fieldref:
    fieldpath: data.namespace
  name: namespace
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: cert-manager-parameters
