---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cert-manager
  name: cert-manager
spec:
  ports:
  - port: 9402
    protocol: TCP
    targetPort: 9402
  selector:
    app: cert-manager
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: webhook
  name: cert-manager-webhook
spec:
  ports:
  - name: https
    port: 443
    targetPort: 6443
  selector:
    app: webhook
  type: ClusterIP
