---
apiVersion: v1
imagePullSecrets:
- name: artifactory-registry-secret
kind: ServiceAccount
metadata:
  labels:
    app: cainjector
  name: cert-manager-cainjector
---
apiVersion: v1
imagePullSecrets:
- name: artifactory-registry-secret
kind: ServiceAccount
metadata:
  labels:
    app: cert-manager
  name: cert-manager
---
apiVersion: v1
imagePullSecrets:
- name: artifactory-registry-secret
kind: ServiceAccount
metadata:
  labels:
    app: webhook
  name: cert-manager-webhook
