---
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app.kubernetes.io/component: katib
  app.kubernetes.io/name: katib-crds
kind: Kustomization
namespace: kubeflow
resources:
- ../../katib-crds/base/experiment-crd.yaml
- ../../katib-crds/base/suggestion-crd.yaml
- ../../katib-crds/base/trial-crd.yaml
- ../../katib-crds/overlays/application/application.yaml
