---
bases:
- ../../base
configMapGenerator:
- behavior: merge
  envs:
  - params.env
  name: admission-webhook-parameters
configurations:
- params.yaml
generatorOptions:
  disableNameSuffixHash: true
patchesStrategicMerge:
- mutating-webhook-configuration.yaml
- deployment.yaml
resources:
- certificate.yaml
vars:
- fieldref:
    fieldpath: data.issuer
  name: podDefaultsIssuer
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: admission-webhook-parameters
- fieldref:
    fieldpath: metadata.name
  name: podDefaultsCertName
  objref:
    group: cert-manager.io
    kind: Certificate
    name: admission-webhook-cert
    version: v1alpha2
