---
apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
- envs:
  - params.env
  name: dex-parameters
configurations:
- params.yaml
generatorOptions:
  disableNameSuffixHash: true
images:
- name: docker.artifactory.ikarem.io/user/ravi/kubeflow/dexidp/dex
  newName: docker.artifactory.ikarem.io/user/ravi/kubeflow/dexidp/dex
  newTag: v2.22.0
kind: Kustomization
namespace: auth
resources:
- namespace.yaml
- config-map.yaml
- crds.yaml
- deployment.yaml
- service.yaml
vars:
- fieldref:
    fieldpath: data.dex_domain
  name: dex_domain
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: dex-parameters
- fieldref:
    fieldpath: data.issuer
  name: issuer
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: dex-parameters
- fieldref:
    fieldpath: data.static_email
  name: static_email
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: dex-parameters
- fieldref:
    fieldpath: data.static_password_hash
  name: static_password_hash
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: dex-parameters
- fieldref:
    fieldpath: data.static_username
  name: static_username
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: dex-parameters
- fieldref:
    fieldpath: data.static_user_id
  name: static_user_id
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: dex-parameters
- fieldref:
    fieldpath: data.client_id
  name: client_id
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: dex-parameters
- fieldref:
    fieldpath: data.oidc_redirect_uris
  name: oidc_redirect_uris
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: dex-parameters
- fieldref:
    fieldpath: data.application_secret
  name: application_secret
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: dex-parameters
