---
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app.kubernetes.io/component: ml-pipeline
  app.kubernetes.io/name: kubeflow-pipelines
kind: Kustomization
namespace: kubeflow
patchesJson6902:
- path: application-patch.json
  target:
    group: app.k8s.io
    kind: Application
    name: kubeflow-pipelines
    version: v1beta1
patchesStrategicMerge:
- api-service/deployment-patch.yaml
- pipelines-ui/deployment-patch.yaml
- pipelines-ui/configmap-patch.yaml
- scheduled-workflow/deployment-patch.yaml
- viewer-controller/deployment-patch.yaml
- persistence-agent/deployment-patch.yaml
- metadata-writer/deployment-patch.yaml
- cache/deployment-patch.yaml
resources:
- ../generic
- api-service
- pipelines-ui
- pipelines-profile-controller
- scheduled-workflow
- viewer-controller
- persistence-agent
- cache
- metadata-writer
- istio-authorization-config.yaml
