---
apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
- envs:
  - params.env
  name: parameters
configurations:
- params.yaml
generatorOptions:
  disableNameSuffixHash: true
images:
- name: docker.artifactory.ikarem.io/user/ravi/kubeflow/kubeflow-images-public/kubernetes-sigs/application
  newName: docker.artifactory.ikarem.io/user/ravi/kubeflow/kubeflow-images-public/kubernetes-sigs/application
  newTag: 1.0-beta
kind: Kustomization
nameprefix: application-controller-
namespace: kubeflow
resources:
- cluster-role.yaml
- cluster-role-binding.yaml
- service-account.yaml
- service.yaml
- stateful-set.yaml
vars:
- fieldref:
    fieldpath: data.project
  name: project
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: parameters
