---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful-set
spec:
  selector:
    matchLabels:
      app: application-controller
  serviceName: service
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'false'
      labels:
        app: application-controller
    spec:
      containers:
      - command:
        - /root/manager
        env:
        - name: project
          value: $(project)
        image: docker.artifactory.ikarem.io/user/ravi/kubeflow/kubeflow-images-public/kubernetes-sigs/application:1.0-beta
        imagePullPolicy: Always
        name: manager
        resources:
          limits:
            memory: 300Mi
          requests:
            cpu: 50m
            memory: 300Mi
      serviceAccountName: service-account
  volumeClaimTemplates: []
