---
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  kustomize.component: metadata
configMapGenerator:
- envs:
  - params.env
  name: ui-parameters
- envs:
  - grpc-params.env
  name: grpc-configmap
generatorOptions:
  disableNameSuffixHash: true
images:
- name: docker.artifactory.ikarem.io/user/ravi/kubeflow/ml-pipeline/envoy
  newName: docker.artifactory.ikarem.io/user/ravi/kubeflow/ml-pipeline/envoy
  newTag: metadata-grpc
kind: Kustomization
namePrefix: metadata-
namespace: kubeflow
resources:
- metadata-deployment.yaml
- metadata-service.yaml
- metadata-ui-deployment.yaml
- metadata-ui-role.yaml
- metadata-ui-rolebinding.yaml
- metadata-ui-sa.yaml
- metadata-ui-service.yaml
- metadata-envoy-deployment.yaml
- metadata-envoy-service.yaml
vars:
- fieldref:
    fieldpath: metadata.namespace
  name: ui-namespace
  objref:
    apiVersion: v1
    kind: Service
    name: ui
- fieldref:
    fieldpath: data.uiClusterDomain
  name: ui-clusterDomain
  objref:
    kind: ConfigMap
    name: ui-parameters
    version: v1
- fieldref:
    fieldpath: metadata.name
  name: metadata-service
  objref:
    apiVersion: v1
    kind: Service
    name: ui
- fieldref:
    fieldpath: metadata.name
  name: metadata-envoy-service
  objref:
    apiVersion: v1
    kind: Service
    name: envoy-service
