---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: metadata-ui
  name: ui
spec:
  selector:
    matchLabels:
      app: metadata-ui
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'false'
      labels:
        app: metadata-ui
      name: ui
    spec:
      containers:
      - image: docker.artifactory.ikarem.io/user/ravi/kubeflow/kubeflow-images-public/metadata-frontend:v0.1.8
        imagePullPolicy: IfNotPresent
        name: metadata-ui
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: 300Mi
          requests:
            cpu: 50m
            memory: 300Mi
      serviceAccountName: ui
