---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: envoy
  name: envoy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: envoy
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'false'
      labels:
        component: envoy
    spec:
      containers:
      - image: docker.artifactory.ikarem.io/user/ravi/kubeflow/ml-pipeline/envoy:metadata-grpc
        name: container
        ports:
        - containerPort: 9090
          name: md-envoy
        - containerPort: 9901
          name: envoy-admin
        resources:
          limits:
            memory: 300Mi
          requests:
            cpu: 50m
            memory: 300Mi
