---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: server
  name: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'false'
      labels:
        component: server
    spec:
      containers:
      - command:
        - ./server/server
        - --http_port=8080
        image: docker.artifactory.ikarem.io/user/ravi/kubeflow/kubeflow-images-public/metadata:v0.1.11
        livenessProbe:
          httpGet:
            httpHeaders:
            - name: ContentType
              value: application/json
            path: /api/v1alpha1/artifact_types
            port: backendapi
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 2
        name: container
        ports:
        - containerPort: 8080
          name: backendapi
        readinessProbe:
          httpGet:
            httpHeaders:
            - name: ContentType
              value: application/json
            path: /api/v1alpha1/artifact_types
            port: backendapi
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 2
        resources:
          limits:
            memory: 300Mi
          requests:
            cpu: 50m
            memory: 300Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: grpc-server
  name: grpc-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: grpc-server
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'false'
      labels:
        component: grpc-server
    spec:
      containers:
      - args:
        - --grpc_port=$(METADATA_GRPC_SERVICE_PORT)
        command:
        - /bin/metadata_store_server
        envFrom:
        - configMapRef:
            name: grpc-configmap
        image: docker.artifactory.ikarem.io/user/ravi/kubeflow/tfx-oss-public/ml_metadata_store_server:v0.21.1
        name: container
        ports:
        - containerPort: 8080
          name: grpc-backendapi
        resources:
          limits:
            memory: 300Mi
          requests:
            cpu: 50m
            memory: 300Mi
