---
apiVersion: kustomize.config.k8s.io/v1beta1
images:
- name: docker.artifactory.ikarem.io/user/ravi/kubeflow/ml-pipeline/metadata-writer
  newName: docker.artifactory.ikarem.io/user/ravi/kubeflow/ml-pipeline/metadata-writer
  newTag: 1.0.0
kind: Kustomization
resources:
- metadata-writer-deployment.yaml
- metadata-writer-role.yaml
- metadata-writer-rolebinding.yaml
- metadata-writer-sa.yaml
