---
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  kustomize.component: profiles
configMapGenerator:
- literals:
  - admin=
  - gcp-sa=
  name: profiles-config
images:
- name: docker.artifactory.ikarem.io/user/ravi/kubeflow/kubeflow-images-public/profile-controller
  newName: docker.artifactory.ikarem.io/user/ravi/kubeflow/kubeflow-images-public/profile-controller
  newTag: vmaster-g34aa47c2
- name: docker.artifactory.ikarem.io/user/ravi/kubeflow/kubeflow-images-public/kfam
  newName: docker.artifactory.ikarem.io/user/ravi/kubeflow/kubeflow-images-public/kfam
  newTag: v1.1.0-g9f3bfd00
kind: Kustomization
namePrefix: profiles-
patchesStrategicMerge:
- deployment_patch.yaml
resources:
- ../base/cluster-role-binding.yaml
- ../base/crd.yaml
- ../base/deployment.yaml
- ../base/service.yaml
- ../base/service-account.yaml
- ../overlays/istio/virtual-service.yaml
- ../overlays/application/application.yaml
