---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mpi-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mpi-operator
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'false'
      labels:
        app: mpi-operator
    spec:
      containers:
      - args:
        - -alsologtostderr
        - --lock-namespace
        - $(lock-namespace)
        - --kubectl-delivery-image
        - $(kubectl-delivery-image)
        image: docker.artifactory.ikarem.io/user/ravi/kubeflow/mpi-operator:latest
        imagePullPolicy: Always
        name: mpi-operator
        resources:
          limits:
            memory: 300Mi
          requests:
            cpu: 50m
            memory: 300Mi
      serviceAccountName: mpi-operator
