---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'false'
    spec:
      containers:
      - image: docker.artifactory.ikarem.io/user/ravi/kubeflow/kubeflow-images-public/jupyter-web-app:vmaster-gd9be4b9e
        name: jupyter-web-app
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: 300Mi
          requests:
            cpu: 50m
            memory: 300Mi
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      serviceAccountName: service-account
      volumes:
      - configMap:
          name: jupyter-web-app-config
        name: config-volume
