---
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: jupyter-web-app
  kustomize.component: jupyter-web-app
configMapGenerator:
- envs:
  - params.env
  name: parameters
- files:
  - configs/spawner_ui_config.yaml
  name: jupyter-web-app-config
configurations:
- params.yaml
generatorOptions:
  disableNameSuffixHash: true
images:
- name: docker.artifactory.ikarem.io/user/ravi/kubeflow/kubeflow-images-public/jupyter-web-app
  newName: docker.artifactory.ikarem.io/user/ravi/kubeflow/kubeflow-images-public/jupyter-web-app
  newTag: vmaster-gd9be4b9e
kind: Kustomization
namePrefix: jupyter-web-app-
namespace: kubeflow
patchesStrategicMerge:
- deployment_patch.yaml
resources:
- cluster-role-binding.yaml
- cluster-role.yaml
- deployment.yaml
- role-binding.yaml
- role.yaml
- service-account.yaml
- service.yaml
vars:
- fieldref:
    fieldPath: data.policy
  name: policy
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: parameters
- fieldref:
    fieldPath: data.prefix
  name: prefix
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: parameters
- fieldref:
    fieldPath: data.clusterDomain
  name: clusterDomain
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: parameters
- fieldref:
    fieldPath: metadata.namespace
  name: namespace
  objref:
    apiVersion: v1
    kind: Service
    name: service
- fieldref:
    fieldPath: data.userid-header
  name: userid-header
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: parameters
- fieldref:
    fieldPath: data.userid-prefix
  name: userid-prefix
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: parameters
