---
apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: "---\napiVersion: ambassador/v0\nkind:  Mapping\nname:\
      \ webapp_mapping\nprefix: /$(prefix)/\nservice: jupyter-web-app-service.$(namespace)\n\
      add_request_headers:\n  x-forwarded-prefix: /jupyter"
  labels:
    run: jupyter-web-app
  name: service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  type: ClusterIP
