---
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: notebook-controller
  kustomize.component: notebook-controller
configMapGenerator:
- envs:
  - params.env
  name: parameters
generatorOptions:
  disableNameSuffixHash: true
images:
- name: docker.artifactory.ikarem.io/user/ravi/kubeflow/kubeflow-images-public/notebook-controller
  newName: docker.artifactory.ikarem.io/user/ravi/kubeflow/kubeflow-images-public/notebook-controller
  newTag: vmaster-gf39279c0
kind: Kustomization
namePrefix: notebook-controller-
namespace: kubeflow
patchesStrategicMerge:
- deployment_patch.yaml
resources:
- cluster-role-binding.yaml
- cluster-role.yaml
- crd.yaml
- deployment.yaml
- service-account.yaml
- service.yaml
vars:
- fieldref:
    fieldPath: data.USE_ISTIO
  name: USE_ISTIO
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: parameters
- fieldref:
    fieldPath: data.ISTIO_GATEWAY
  name: ISTIO_GATEWAY
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: parameters
