---
configMapGenerator:
- envs:
  - params.env
  name: istio-install-parameters
configurations:
- params.yaml
images:
- name: docker.artifactory.ikarem.io/user/ravi/kubeflow/istio-release/citadel
  newName: docker.artifactory.ikarem.io/user/ravi/kubeflow/istio-release/citadel
  newTag: release-1.3-latest-daily
- name: docker.artifactory.ikarem.io/user/ravi/kubeflow/istio-release/galley
  newName: docker.artifactory.ikarem.io/user/ravi/kubeflow/istio-release/galley
  newTag: release-1.3-latest-daily
- name: docker.artifactory.ikarem.io/user/ravi/kubeflow/istio-release/proxyv2
  newName: docker.artifactory.ikarem.io/user/ravi/kubeflow/istio-release/proxyv2
  newTag: release-1.3-latest-daily
- name: docker.artifactory.ikarem.io/user/ravi/kubeflow/istio-release/pilot
  newName: docker.artifactory.ikarem.io/user/ravi/kubeflow/istio-release/pilot
  newTag: release-1.3-latest-daily
- name: docker.artifactory.ikarem.io/user/ravi/kubeflow/istio-release/proxyv2
  newName: docker.artifactory.ikarem.io/user/ravi/kubeflow/istio-release/proxyv2
  newTag: release-1.3-latest-daily
- name: docker.artifactory.ikarem.io/user/ravi/kubeflow/istio-release/mixer
  newName: docker.artifactory.ikarem.io/user/ravi/kubeflow/istio-release/mixer
  newTag: release-1.3-latest-daily
- name: docker.artifactory.ikarem.io/user/ravi/kubeflow/istio-release/proxyv2
  newName: docker.artifactory.ikarem.io/user/ravi/kubeflow/istio-release/proxyv2
  newTag: release-1.3-latest-daily
- name: docker.artifactory.ikarem.io/user/ravi/kubeflow/istio-release/sidecar_injector
  newName: docker.artifactory.ikarem.io/user/ravi/kubeflow/istio-release/sidecar_injector
  newTag: release-1.3-latest-daily
- name: docker.artifactory.ikarem.io/user/ravi/kubeflow/istio-release/mixer
  newName: docker.artifactory.ikarem.io/user/ravi/kubeflow/istio-release/mixer
  newTag: release-1.3-latest-daily
- name: docker.artifactory.ikarem.io/user/ravi/kubeflow/istio-release/proxyv2
  newName: docker.artifactory.ikarem.io/user/ravi/kubeflow/istio-release/proxyv2
  newTag: release-1.3-latest-daily
- name: docker.artifactory.ikarem.io/user/ravi/kubeflow/prom/prometheus
  newName: docker.artifactory.ikarem.io/user/ravi/kubeflow/prom/prometheus
  newTag: v2.8.0
resources:
- namespace.yaml
- attribute-manifest.yaml
- config-map.yaml
- cluster-role.yaml
- cluster-role-binding.yaml
- daemon-set.yaml
- deployment.yaml
- handler.yaml
- horizontal-pod-autoscaler.yaml
- instance.yaml
- job.yaml
- mutating-webhook-configuration.yaml
- pod-disruption-budget.yaml
- role.yaml
- role-binding.yaml
- rule.yaml
- service.yaml
- service-account.yaml
- service-role.yaml
- service-role-binding.yaml
vars:
- fieldref:
    fieldpath: data.namespace
  name: namespace
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: istio-install-parameters
