---
apiVersion: v1
imagePullSecrets:
- name: artifactory-registry-secret
kind: ServiceAccount
metadata:
  name: argo
---
apiVersion: v1
imagePullSecrets:
- name: artifactory-registry-secret
kind: ServiceAccount
metadata:
  name: argo-ui
  namespace: kubeflow
