---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'false'
    spec:
      containers:
      - args:
        - -userid-header
        - $(userid-header)
        - -userid-prefix
        - $(userid-prefix)
        - -workload-identity
        - $(gcp-sa)
        command:
        - /manager
        image: docker.artifactory.ikarem.io/user/ravi/kubeflow/kubeflow-images-public/profile-controller:vmaster-g34aa47c2
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /metrics
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        name: manager
        ports:
        - containerPort: 8080
          name: manager-http
          protocol: TCP
        resources:
          limits:
            memory: 300Mi
          requests:
            cpu: 50m
            memory: 300Mi
      - args:
        - -cluster-admin
        - $(admin)
        - -userid-header
        - $(userid-header)
        - -userid-prefix
        - $(userid-prefix)
        command:
        - /access-management
        image: docker.artifactory.ikarem.io/user/ravi/kubeflow/kubeflow-images-public/kfam:v1.1.0-g9f3bfd00
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /metrics
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 30
        name: kfam
        ports:
        - containerPort: 8081
          name: kfam-http
          protocol: TCP
        resources:
          limits:
            memory: 300Mi
          requests:
            cpu: 50m
            memory: 300Mi
      serviceAccountName: controller-service-account
