---
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  kustomize.component: profiles
configMapGenerator:
- envs:
  - params.env
  name: profiles-parameters
configurations:
- params.yaml
images:
- name: docker.artifactory.ikarem.io/user/ravi/kubeflow/kubeflow-images-public/profile-controller
  newName: docker.artifactory.ikarem.io/user/ravi/kubeflow/kubeflow-images-public/profile-controller
  newTag: vmaster-g34aa47c2
- name: docker.artifactory.ikarem.io/user/ravi/kubeflow/kubeflow-images-public/kfam
  newName: docker.artifactory.ikarem.io/user/ravi/kubeflow/kubeflow-images-public/kfam
  newTag: v1.1.0-g9f3bfd00
kind: Kustomization
namePrefix: profiles-
namespace: kubeflow
resources:
- cluster-role-binding.yaml
- crd.yaml
- deployment.yaml
- service.yaml
- service-account.yaml
vars:
- fieldref:
    fieldPath: data.admin
  name: admin
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: profiles-parameters
- fieldref:
    fieldPath: data.gcp-sa
  name: gcp-sa
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: profiles-parameters
- fieldref:
    fieldPath: data.userid-header
  name: userid-header
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: profiles-parameters
- fieldref:
    fieldPath: data.userid-prefix
  name: userid-prefix
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: profiles-parameters
- fieldref:
    fieldPath: metadata.namespace
  name: namespace
  objref:
    apiVersion: v1
    kind: Service
    name: kfam
