---
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app.kubernetes.io/component: katib
  app.kubernetes.io/name: katib-controller
images:
- name: docker.artifactory.ikarem.io/user/ravi/kubeflow/kubeflow-images-public/katib/v1alpha3/katib-db-manager
  newName: docker.artifactory.ikarem.io/user/ravi/kubeflow/kubeflow-images-public/katib/v1alpha3/katib-db-manager
  newTag: 917164a
kind: Kustomization
namespace: kubeflow
resources:
- ../../katib-controller/base/katib-db-manager-deployment.yaml
- ../../katib-controller/base/katib-db-manager-service.yaml
