---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ml-pipeline-viewer-crd
  name: ml-pipeline-viewer-crd
spec:
  selector:
    matchLabels:
      app: ml-pipeline-viewer-crd
  template:
    metadata:
      labels:
        app: ml-pipeline-viewer-crd
    spec:
      containers:
      - env:
        - name: MAX_NUM_VIEWERS
          value: '50'
        - name: MINIO_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: docker.artifactory.ikarem.io/user/ravi/kubeflow/ml-pipeline/viewer-crd-controller:1.0.0
        imagePullPolicy: Always
        name: ml-pipeline-viewer-crd
        resources:
          limits:
            memory: 300Mi
          requests:
            cpu: 50m
            memory: 300Mi
      serviceAccountName: ml-pipeline-viewer-crd-service-account
