---
apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- ../../base
commonLabels:
  kustomize.component: metadata
configMapGenerator:
- envs:
  - params.env
  name: metadata-db-parameters
generatorOptions:
  disableNameSuffixHash: true
images:
- name: docker.artifactory.ikarem.io/user/ravi/kubeflow/ml-pipeline/envoy
  newName: docker.artifactory.ikarem.io/user/ravi/kubeflow/ml-pipeline/envoy
  newTag: metadata-grpc
kind: Kustomization
namespace: kubeflow
patchesStrategicMerge:
- metadata-deployment.yaml
resources:
- metadata-db-pvc.yaml
- metadata-db-deployment.yaml
- metadata-db-service.yaml
vars:
- fieldref:
    fieldpath: metadata.name
  name: metadata-db-service
  objref:
    apiVersion: v1
    kind: Service
    name: metadata-db
