---
apiVersion: v1
kind: Service
metadata:
  labels:
    component: db
  name: metadata-db
spec:
  ports:
  - name: dbapi
    port: 3306
    protocol: TCP
  selector:
    component: db
  type: ClusterIP
