---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: db
  name: metadata-db
spec:
  replicas: 1
  selector:
    matchLabels:
      component: db
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'false'
      labels:
        component: db
      name: db
    spec:
      containers:
      - args:
        - --datadir
        - /var/lib/mysql/datadir
        envFrom:
        - configMapRef:
            name: metadata-db-parameters
        - secretRef:
            name: metadata-db-secrets
        image: docker.artifactory.ikarem.io/user/ravi/kubeflow/mysql:8.0.3
        name: db-container
        ports:
        - containerPort: 3306
          name: dbapi
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - mysql -D $$MYSQL_DATABASE -p$$MYSQL_ROOT_PASSWORD -e 'SELECT 1'
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1
        resources:
          limits:
            memory: 600Mi
          requests:
            cpu: 300m
            memory: 600Mi
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: metadata-mysql
      volumes:
      - name: metadata-mysql
        persistentVolumeClaim:
          claimName: metadata-mysql
