---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'false'
    spec:
      containers:
      - image: docker.artifactory.ikarem.io/user/ravi/kubeflow/kubeflow-images-public/admission-webhook:vmaster-gaf96e4e3
        name: admission-webhook
        resources:
          limits:
            memory: 300Mi
          requests:
            cpu: 50m
            memory: 300Mi
        volumeMounts:
        - mountPath: /etc/webhook/certs
          name: webhook-cert
          readOnly: true
      serviceAccountName: service-account
      volumes:
      - name: webhook-cert
        secret:
          secretName: webhook-certs
