---
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: admission-webhook
  kustomize.component: admission-webhook
configMapGenerator:
- envs:
  - params.env
  name: admission-webhook-parameters
configurations:
- params.yaml
generatorOptions:
  disableNameSuffixHash: true
images:
- name: docker.artifactory.ikarem.io/user/ravi/kubeflow/kubeflow-images-public/admission-webhook
  newName: docker.artifactory.ikarem.io/user/ravi/kubeflow/kubeflow-images-public/admission-webhook
  newTag: vmaster-gaf96e4e3
kind: Kustomization
namePrefix: admission-webhook-
namespace: kubeflow
resources:
- cluster-role-binding.yaml
- cluster-role.yaml
- deployment.yaml
- mutating-webhook-configuration.yaml
- service-account.yaml
- service.yaml
- crd.yaml
vars:
- fieldref:
    fieldPath: data.namespace
  name: podDefaultsNamespace
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: admission-webhook-parameters
- fieldref:
    fieldPath: metadata.name
  name: podDefaultsServiceName
  objref:
    apiVersion: v1
    kind: Service
    name: service
- fieldref:
    fieldPath: metadata.name
  name: podDefaultsDeploymentName
  objref:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment
