---
apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- ../../base
configMapGenerator:
- behavior: merge
  envs:
  - params.env
  name: dex-parameters
configurations:
- params.yaml
generatorOptions:
  disableNameSuffixHash: true
kind: Kustomization
resources:
- virtual-service.yaml
vars:
- fieldref:
    fieldpath: data.namespace
  name: namespace
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: dex-parameters
