---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: 'true'
        image: docker.artifactory.ikarem.io/user/ravi/kubeflow/ml-pipeline/mysql:5.6
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
        resources:
          limits:
            memory: 600Mi
          requests:
            cpu: 300m
            memory: 600Mi
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-persistent-storage
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
